#!/bin/bash
#=============IMPORTANT==================
progress_file="progress.txt"

# Creates file if missing
if [ ! -f "$progress_file" ]; then
    echo -e "easy=0\nmedium=0\nhard=0\neasy_best=999\nmedium_best=999\nhard_best=999\nultra_best=999\nbaby_best=999" > "$progress_file"
fi
# Loads values(So now I can use them as variables)
source "$progress_file"

save_progress() {
    echo -e "easy=$easy\nmedium=$medium\nhard=$hard\n\
 easy_best=$easy_best\nmedium_best=$medium_best\nhard_best=$hard_best\nultra_best=$ultra_best\nbaby_best=$baby_best" > "$progress_file"
}

load_progress() {
    source "$progress_file"
    easy=${easy:-0}
    medium=${medium:-0}
    hard=${hard:-0}
    easy_best=${easy_best:-999}
    medium_best=${medium_best:-999}
    hard_best=${hard_best:-999}
    ultra_best=${ultra_best:-999}
    baby_best=${baby_best:-999}
}
#==============UTILITIES=================
cls() {
    clear
}
blink() {
    local text="$1"
    local times="${2:-3}"

    for ((i=0; i<times; i++)); do
        printf "\r\033[1;31m%s\033[0m" "$text"
        sleep 0.4
        printf "\r%*s\r" "${#text}" ""
        sleep 0.4
    done
}
confirm_exit() {
    echo
    read -rp "Are you sure you want to quit to menu? (Y/N): " ans
    ans=$(echo "$ans" | tr '[:upper:]' '[:lower:]')

    case "$ans" in
        y|yes)
            echo "Returning to menu..."
            sleep 1
            menu
            ;;
        *)
            echo "Resuming game..."
            cls
            printf "Enter Guess: "
            ;;
    esac
}
cleanup() {
    cls
    echo "Shutting Down..."
    sleep 1
    cls
    exit
}
minigame_exit() {
    minigames_menu
}
mm_exit() {
    menu
}
check_exit() {
    #variable=$1
    #exit_func=$2
    if [[ $1 = "exit" ]]; then
        $2
    fi
}
#=====================================
#============== COLORS ==============
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color
#==================Main Code=============================
#------Game------
game() {
    trap 'confirm_exit' SIGINT
    cls
    won=false
    hints=false
    babymode=false
    ultramode=false
    tries=0
    range="$1"
    name="$2"
    start_lives="$3"
    lives="$start_lives"
    hints="${4:-false}"
    babymode="${5:-false}"
    ultramode="${6:-false}"
    if [[ "$ultramode" = true || "$babymode" = true ]]; then
        trap 'minigame_exit' SIGINT
    fi
    num=$(($RANDOM % $range))
    echo -e "${RED}$name Mode!\nRange: (0-$((range-1)))${NC}"
    while (($lives > 0)); do
        echo "-----------------------------"
        read -rp "Guess(0-$((range-1))): " guess
        # Removes whitespace
        guess="${guess//[[:space:]]/}"
        if [[ "$babymode" == true || "$ultramode" == true ]]; then
            check_exit "$guess" "minigame_exit"
        fi
        
        check_exit "$guess" "confirm_exit"
        
        if [[ -z "$guess" ]]; then
            echo "You didn't enter anything"
            continue
        fi
        if ! [[ "$guess" =~ ^[0-9]+$ ]]; then
            echo -e "${RED}Invalid input. Please enter a whole/positive number.${NC}"
            continue
        fi
        ((tries++))
        if [[ "$guess" -eq "$num" ]]; then
            if [[ "$babymode" == true ]]; then
                if [[ "$tries" -eq 1 ]]; then
                    echo -e "${BLUE}You got the number in $tries try, BOOOOOOOOOO!${NC}"
                else
                    echo -e "${BLUE}You got the number in $tries tries, HAHAHAHHAHAAHHAH${NC}"
                fi
                sleep 1.2
                won=true
                break
            fi
            if [[ "$tries" -eq 1 ]]; then
                echo -e "${YELLOW}You got the number in $tries try!${NC}"
            else
                echo -e "${GREEN}You got the number in $tries tries!${NC}"
            fi
            won=true
            break
        else
            ((lives--))
            echo "-----------------------------"
            printf "\n${RED}Wrong Number!${NC}\n"
            if [[ "$hints" == true ]]; then
                if [[ $guess -gt $num ]]; then
                    echo -e "${BLUE}Too High${NC}"
                else
                    echo -e "${BLUE}Too Low${NC}"
                fi
            fi
            echo -e "${CYAN}Lives: $lives${NC}"

            if [[ "$lives" -eq 1 ]]; then
                blink "====LOW LIVES!===="
            fi
        fi
    done
    echo "-----------------------------"
    if [[ "$won" == true ]]; then
        case "$name" in
        Easy)
            easy=1
            if ((tries < easy_best)); then
                easy_best=$tries
                echo -e "${YELLOW}New BEST score for Easy: $tries tries!${NC}"
            fi
            ;;
        Medium)
            medium=1
            if ((tries < medium_best)); then
                medium_best=$tries
                echo -e "${YELLOW}New BEST score for Medium: $tries tries!${NC}"
            fi
            ;;
        Hard)
            hard=1
            if ((tries < hard_best)); then
                hard_best=$tries
                echo -e "${YELLOW}New BEST score for Hard: $tries tries!${NC}"
            fi
            ;;
        Ultramode)
            if ((tries < ultra_best)); then
                ultra_best=$tries
                echo -e "${YELLOW}New BEST score for Ultramode: $tries tries!${NC}"
                fi;;
        Babymode)
                if ((tries < baby_best)); then
                    baby_best=$tries
                    echo -e "${YELLOW}New BEST score for Babymode: $tries tries!${NC}"
                fi;;
    esac
        echo -e "${GREEN}Difficulty '$name' completed!${NC}"
        save_progress
    fi
    read -rp "Play again(Y/N): " pa
    case $pa in
        y|yes)
            if [[ "$won" == true ]]; then
                read -rp "Same game(Y/N): " sg
                sg=$(echo "$sg" | tr "[:upper:]" "[:lower:]")
                case $sg in
                    y|yes) game "$range" "$name" "$start_lives" "$hints";;
                
                    *) 
                        trap "cleanup" SIGINT
                        menu;;
                esac
            fi
    esac
    pa=$(echo "$pa" | tr '[:upper:]' '[:lower:]')
    case $pa in
        y|yes)
            game "$range" "$name" "$start_lives" "$hints"
            ;;
        *)
            trap "cleanup" SIGINT
            menu;;
    esac
}

#-----------------
#----------MINIGAMES------------
minigames_menu() {
    cls
    trap "mm_exit" SIGINT

    echo -e "${CYAN}=========================
        MINIGAMES
=========================${NC}"

    echo -e "${CYAN}Whatever:${NC}"
    echo "Babymode: $baby_best, :/"
    echo "Ultramode: $ultra_best"
    options=(
    "1) Babymode"
    "2) Ultramode"
    "3) Dice Roll"
    "4) Math Quiz"
    "5) Back to Main Menu"
    
    )

    for opt in "${options[@]}"; do
        echo "$opt"
    done
    
    read -rp ": " choice
    choice=$(echo "$choice" | tr '[:upper:]' '[:lower:]')
    case $choice in
        1|babymode) game 5 Babymode 2 false true;;
        1h|babymodeh) 
            echo "Nope, bum."
            sleep 1.8
            game 5 Babymode 2 false true;;
        2|ultramode) game 100000000 "Ultramode" 100 false false true;;
        2h|ultramodeh) echo -e "NO HINTS FOR YOU HAHAHAHAH"
                        sleep 1
                        game 100000000 "Ultramode >:)" 50 true false true;;
        3|"dice game"|"dice roll") dice_game;;
        4|"math quiz") math_quiz;;
        5|menu|"exit") menu;;
        *)
            echo "Invalid option"
            sleep 1
            minigames_menu
            ;;
    esac
}

# AI creation
dice_game() {
    trap "minigame_exit" SIGINT
    cls
    echo -e "${BLUE}--- Dice Roll Game ---${NC}"
    player=$((RANDOM % 6 + 1))
    cpu=$((RANDOM % 6 + 1))
    echo "You rolled: $player"
    sleep 1
    echo "Computer rolled: $cpu"
    if ((player > cpu)); then
        echo -e "${GREEN}You win!${NC}"
    elif ((player < cpu)); then
        echo -e "${RED}You lose!${NC}"
    else
        echo -e "${YELLOW}It's a tie!${NC}"
    fi
    read -rp "Press Enter to play again or CTRL C/type 'exit' to return..." pla
    check_exit $pla "minigame_exit"
    sleep 1
    dice_game
}
# AI Creation
math_quiz() {
    trap "minigame_exit" SIGINT
    cls
    echo -e "${BLUE}--- Math Quiz ---${NC}"
    a=$((RANDOM % 10 + 1))
    b=$((RANDOM % 10 + 1))
    op=$((RANDOM % 2))
    if ((op == 0)); then
        answer=$((a + b))
        symbol="+"
    else
        answer=$((a * b))
        symbol="*"
    fi
    read -rp "What is $a $symbol $b? " user
    check_exit $user "minigame_exit"
    if [[ "$user" == "$answer" ]]; then
        echo -e "${GREEN}Correct!${NC}"
    else
        echo -e "${RED}Wrong! Answer was $answer${NC}"
    fi
    read -rp "Press Enter to play again or CTRL C/type 'exit' to return..." pla
    check_exit $pla "minigame_exit"
    math_quiz
}
#---Main Menu----
menu() {
    cls
    trap "cleanup" SIGINT
    echo -e "${CYAN}=========================
    GUESS NUMBER GAME
    
    CTRL C to Quit/Shutdown
    Or type \"Exit\"
=========================${NC}"
    echo -e "${CYAN}Best Scores:${NC}"
    echo "Easy:   $easy_best tries"
    echo "Medium: $medium_best tries"
    echo "Hard:   $hard_best tries"
    echo
    dif=("1) Easy(0-9)" "2) Medium(0-49)" "3) Hard(0-99)"  "4) Minigames" "Hints: Add \"h\" at the end of your choice")
    echo -e "${BLUE}Choose a dificulty:${NC} "
    for x in "${dif[@]}";
        do
            echo "$x"
        done
    #--------------
    read -p ": " op
    op=$(echo "$op" | tr '[:upper:]' '[:lower:]')
    case $op in
        1|easy) game 10 Easy 5;;
        2|medium) game 50 Medium 10;;
        3|hard) game 100 Hard 20;;
        1h|easyh) game 10 Easy 5 true;;
        2h|mediumh) game 50 Medium 10 true;;
        3h|hardh) game 100 Hard 20 true;;
        4|minigames)
            load_progress
            if [[ $easy -eq 1 && $medium -eq 1 && $hard -eq 1 ]]; then
                echo -e "${GREEN}Access granted to minigames!${NC}"
                sleep 1
                minigames_menu
                
            else
                echo -e "${RED}You must complete all difficulties first!${NC}"
                sleep 2
                menu
            fi
            ;;
        5|"exit") cleanup;;
        *)
            echo " non of the options"
            sleep 1
            menu
            ;;
    esac
}
menu
#==========================================================
